CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CONSTRAINT_ENABLE`()
BEGIN

ALTER TABLE TBL_FNL_ACTOR ADD CONSTRAINT PK_ACTOR_ID PRIMARY KEY (ACTOR_ID);
ALTER TABLE TBL_FNL_ADDRESS ADD CONSTRAINT PK_ADDRESS_ID PRIMARY KEY (ADDRESS_ID);
ALTER TABLE TBL_FNL_CATEGORY ADD CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (CATEGORY_ID);
ALTER TABLE TBL_FNL_CITY ADD CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID);
ALTER TABLE TBL_FNL_COUNTRY ADD CONSTRAINT PK_COUNTRY_ID PRIMARY KEY (COUNTRY_ID);
ALTER TABLE TBL_FNL_CUSTOMER ADD CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE TBL_FNL_FILM ADD CONSTRAINT PK_FILM_ID PRIMARY KEY (FILM_ID);
ALTER TABLE TBL_FNL_FILM_ACTOR ADD CONSTRAINT PK_F_ACTOR_ID PRIMARY KEY (ACTOR_ID);
ALTER TABLE TBL_FNL_FILM_CATEGORY ADD CONSTRAINT PK_F_CATEGORY_ID PRIMARY KEY (FILM_ID);
ALTER TABLE TBL_FNL_FILM_TEXT ADD CONSTRAINT PK_F_TEXT_ID PRIMARY KEY (FILM_ID);
ALTER TABLE TBL_FNL_INVENTORY ADD CONSTRAINT PK_INVENTORY_ID PRIMARY KEY (INVENTORY_ID);
ALTER TABLE TBL_FNL_LANGUAGE ADD CONSTRAINT PK_LANGUAGE_ID PRIMARY KEY (LANGUAGE_ID);
ALTER TABLE TBL_FNL_PAYMENT ADD CONSTRAINT PK_PAYMENT_ID PRIMARY KEY (PAYMENT_ID);
ALTER TABLE TBL_FNL_RENTAL ADD CONSTRAINT PK_RENTAL_ID PRIMARY KEY (RENTAL_ID);
ALTER TABLE TBL_FNL_STAFF ADD CONSTRAINT PK_STAFF_ID PRIMARY KEY (STAFF_ID);
ALTER TABLE TBL_FNL_STORE ADD CONSTRAINT PK_STORE_ID PRIMARY KEY (STORE_ID);

ALTER TABLE TBL_FNL_ADDRESS
ADD CONSTRAINT FK_ADD_CITY FOREIGN KEY (CITY_ID) REFERENCES TBL_FNL_CITY(CITY_ID);
ALTER TABLE TBL_FNL_CITY
ADD CONSTRAINT FK_CITY_COU FOREIGN KEY (COUNTRY_ID) REFERENCES TBL_FNL_COUNTRY(COUNTRY_ID);
ALTER TABLE TBL_FNL_CUSTOMER
ADD CONSTRAINT FK_CUST_STORE FOREIGN KEY (STORE_ID) REFERENCES TBL_FNL_STORE(STORE_ID);
ALTER TABLE TBL_FNL_CUSTOMER
ADD CONSTRAINT FK_CUST_ADD FOREIGN KEY (ADDRESS_ID) REFERENCES TBL_FNL_ADDRESS(ADDRESS_ID);
ALTER TABLE TBL_FNL_FILM
ADD CONSTRAINT FK_FILM_LANG FOREIGN KEY (LANGUAGE_ID) REFERENCES TBL_FNL_LANGUAGE(LANGUAGE_ID);
ALTER TABLE TBL_FNL_FILM_ACTOR
ADD CONSTRAINT FK_FACTOR_FILM FOREIGN KEY (FILM_ID) REFERENCES TBL_FNL_FILM(FILM_ID);
ALTER TABLE TBL_FNL_INVENTORY
ADD CONSTRAINT FK_INV_FILM FOREIGN KEY (FILM_ID) REFERENCES TBL_FNL_FILM(FILM_ID);
ALTER TABLE TBL_FNL_INVENTORY
ADD CONSTRAINT FK_INV_STORE FOREIGN KEY (STORE_ID) REFERENCES TBL_FNL_FILM(STORE_ID);
ALTER TABLE TBL_FNL_PAYMENT
ADD CONSTRAINT FK_PAY_CUST FOREIGN KEY (CUSTOMER_ID) REFERENCES TBL_FNL_CUSTOMER(CUSTOMER_ID);
ALTER TABLE TBL_FNL_PAYMENT
ADD CONSTRAINT FK_PAY_STAFF FOREIGN KEY (STAFF_ID) REFERENCES TBL_FNL_STAFF(STAFF_ID);
ALTER TABLE TBL_FNL_PAYMENT
ADD CONSTRAINT FK_PAY_RENT FOREIGN KEY (RENTAL_ID) REFERENCES TBL_FNL_RENTAL(RENTAL_ID);
ALTER TABLE TBL_FNL_RENTAL
ADD CONSTRAINT FK_RENT_INV FOREIGN KEY (INVENTORY_ID) REFERENCES TBL_FNL_INVENTORY(INVENTORY_ID);
ALTER TABLE TBL_FNL_RENTAL
ADD CONSTRAINT FK_RENT_CUST FOREIGN KEY (CUSTOMER_ID) REFERENCES TBL_FNL_CUSTOMER(CUSTOMER_ID);
ALTER TABLE TBL_FNL_RENTAL
ADD CONSTRAINT FK_RENT_STAFF FOREIGN KEY (STAFF_ID) REFERENCES TBL_FNL_STAFF(STAFF_ID);
ALTER TABLE TBL_FNL_STAFF
ADD CONSTRAINT FK_STAFF_ADD FOREIGN KEY (ADDRESS_ID) REFERENCES TBL_FNL_ADDRESS(ADDRESS_ID);
ALTER TABLE TBL_FNL_STAFF
ADD CONSTRAINT FK_STAFF_STORE FOREIGN KEY (STORE_ID) REFERENCES TBL_FNL_STORE(STORE_ID);
ALTER TABLE TBL_FNL_STORE
ADD CONSTRAINT FK_STORE_ADD FOREIGN KEY (ADDRESS_ID) REFERENCES TBL_FNL_ADDRESS(ADDRESS_ID);

END